### ISSUE TITLE
gear info table 

### ISSUE THREAD

**Issue by BMO777** [lwunderl/Minnesota-Fish-Explorer#2]
Hi Luke , it's Brian from class and I'm enjoying trying your tool. I'm runnnig into the an error while running the contents of fish_finder_db_schema.sql. There is a missing colon at the query creating the gear info table which is easy to fix and an error while referencing the gear key within that table. Did you mean to make the gear key a unique key?

before:
CREATE TABLE gear_info (
    gear_id SERIAL PRIMARY KEY,
    gear VARCHAR(50) 
)
fixed:
CREATE TABLE gear_info (
    gear_id SERIAL PRIMARY KEY,
    gear VARCHAR(50) UNIQUE
):

**Comment by lwunderl** [comment]
Thanks Brian! I'll update my file. Did it work for you after the changes?

**Comment by BMO777** [comment]
Yes it did, thanks! Now I just have an issue importing the data in fish_cpue_info.csv for some reason. It has alot of nulls
